dist: trusty
language: node_js
node_js:
- 12
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts:
  - 161.35.1.73
branches:
  only:
  - master
env:
  global:
  - REMOTEAPPDIR=/var/www/
  - REMOTEUSER=deploy
  - REMOTEHOST=134.122.15.125
  - PORT=80
install: yarn
script:
- yarn build
notifications:
  email: false
after_success:
- chmod 600 deploy-key && mv deploy-key ~/.ssh/id_rsa
- echo "deploy to 134.122.15.125"
- ssh deploy@134.122.15.125 sh ./push.sh
before_install:
- openssl aes-256-cbc -K $encrypted_92725ca94bf5_key -iv $encrypted_92725ca94bf5_iv
  -in deploy-key.enc -out deploy-key -d
